/*

    IMPORTANT! This file is auto-generated by the Jucer each time you save your
    project - if you alter its contents, your changes may be overwritten!

    If you want to change any of these values, use the Jucer to do so, rather than
    editing this file directly!

    Any commented-out settings will fall back to using the default values that
    they are given in juce_Config.h

*/
 #pragma warning(disable: 4244) //double to float loss of information warning 
 #pragma warning(disable: 4706) //assignment within conditional expression warning 
 #pragma warning(disable: 4996) //vsnprintf warning..

//#define  JUCE_FORCE_DEBUG
//#define  JUCE_LOG_ASSERTIONS
//#define  JUCE_ASIO
//#define  JUCE_WASAPI
//#define  JUCE_DIRECTSOUND
//#define  JUCE_ALSA
#define    JUCE_QUICKTIME 0
//#define  JUCE_OPENGL
//#define  JUCE_USE_FLAC
//#define  JUCE_USE_OGGVORBIS
//#define  JUCE_USE_CDBURNER
//#define  JUCE_USE_CDREADER
//#define  JUCE_USE_CAMERA
//#define  JUCE_ENABLE_REPAINT_DEBUGGING
//#define  JUCE_USE_XINERAMA
//#define  JUCE_USE_XSHM
//#define  JUCE_USE_XRENDER
//#define  JUCE_USE_XCURSOR
//#define  JUCE_PLUGINHOST_VST
//#define  JUCE_PLUGINHOST_AU
//#define  JUCE_ONLY_BUILD_CORE_LIBRARY
//#define  JUCE_WEB_BROWSER
//#define  JUCE_SUPPORT_CARBON
#ifdef DEBUG
#define  JUCE_CHECK_MEMORY_LEAKS 1
#endif
#ifdef NDEBUG
#define  JUCE_CHECK_MEMORY_LEAKS 0
#endif
#define  JUCE_CATCH_UNHANDLED_EXCEPTIONS 1

